version: '2'
services:
    portalui-app:
        image: portalui
        external_links:
            - portalui-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/portalui?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JBOOTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    portalui-mysql:
        extends:
            file: mysql.yml
            service: portalui-mysql
