version: '2'
services:
    portalui-mysql:
        container_name: portalui-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jbooter/PortalUI/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=portalui
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
